domain: hackdiffe.rent
url: https://hackdiffe.rent
theme: jekyll-theme-slate
title: Hack Different
description: The Other Apple Developer Program...
github_username:  hack-different
exclude:
  - .idea/